version: '3'

services:
  postgres:
    container_name: pgem
    image: postgres:alpine
    volumes:
      - ./dump:/dump
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: em
      POSTGRES_USER: em
      POSTGRES_PASSWORD: 7766em

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rmqem
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rgru
      RABBITMQ_DEFAULT_PASS: 159753
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648

  redis:
    image: redis:alpine
    container_name: redisem
    ports:
      - 6378:6379
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  data01:
    driver: local
  uploads:
